#!/usr/bin/env node
// Generoi harnessikohtaiset adapterit neutraaleista lähteistä.
// Aja: node scripts/generate-codex.mjs
//
// LÄHTEET (käsin kirjoitetut, harnessista riippumattomat):
//   marketplace.json
//   <plugari>/plugin.json
//   <plugari>/mcp.json
//
// ADAPTERIT (generoituja — älä muokkaa käsin):
//   .claude-plugin/marketplace.json
//   .agents/plugins/marketplace.json
//   <plugari>/.claude-plugin/plugin.json
//   <plugari>/.codex-plugin/plugin.json
//   <plugari>/.mcp.json                          (Claude Coden löytökuori)
//   <plugari>/skills/<skill>/agents/openai.yaml  (vain MCP:tä tarvitsevat)
//
// MCP standardoi protokollan, ei tiedostonimeä. Neutraali osa on skeema —
// mcpServers-kartta, jonka merkinnät ovat joko stdio tai http — ja se on
// mcp.json:ssa. .mcp.json on olemassa vain siksi, että Claude Code etsii
// juuri sen nimistä tiedostoa plugarin juuresta, joten se generoidaan.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, join } from 'node:path';

import {
  MARKETPLACE_DISPLAY_NAME,
  MARKETPLACE_NAME,
  REPOSITORY,
  ROOT,
  listDirs,
  oneLine,
  parseFrontmatter,
  readJSON as readJSONFile,
  truncate,
} from './lib.mjs';

const CATEGORY = 'Legal';
const GENERATED_HEADER = '# Generated by scripts/generate-codex.mjs.';

function readJSON(path) {
  return readJSONFile(join(ROOT, path));
}

function writeJSON(path, value) {
  const fullPath = join(ROOT, path);
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, `${JSON.stringify(value, null, 2)}\n`);
}

function writeText(path, value) {
  const fullPath = join(ROOT, path);
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, value);
}

function fail(where, message) {
  console.error(`\n✗ ${where}: ${message}\n`);
  process.exit(1);
}

function readSkillMetadata(skillText, fallbackName) {
  const { values } = parseFrontmatter(skillText);
  const name = values.name || fallbackName;
  return { name, description: values.description || name };
}

// Codexin työkaluriippuvuudet päätellään SKILL.md-tekstistä näillä säännöillä.
// Uusi MCP-palvelin tai poikkeus: lisää rivi tähän tauluun — itse
// tunnistuslogiikkaa ei tarvitse muokata.
const DEPENDENCY_RULES = [
  {
    server: 'oik-ai',
    keywords: [
      'oik.ai',
      'finlex-mcp',
      'oikeustutkimus',
      'legal-research',
      'hankintalaki',
      'osakeyhtiölaki',
      'osakeyhtiolaki',
      'oyl ',
      'oiktl',
      'tarkista laki lähteestä',
      'tarkista laki lahteesta',
    ],
    // suomen-kieli mainitsee oikeuslähteet vain esimerkkinä — ei MCP-tarvetta.
    skipSkills: ['juristi/skills/suomen-kieli', 'legal-core/skills/finnish-language'],
  },
  {
    server: 'adeu',
    keywords: ['adeu'],
    skipSkills: [],
  },
  {
    server: 'eu-ai-act',
    keywords: ['eu ai act', 'euaiact', 'tekoälyasetuksen', 'tekoalyasetuksen'],
    skipSkills: [],
  },
];

function detectSkillDependencies(skillText, serverNames, skillPath) {
  const text = skillText.toLocaleLowerCase('fi-FI');
  return DEPENDENCY_RULES
    .filter((rule) =>
      serverNames.includes(rule.server) &&
      !rule.skipSkills.includes(skillPath) &&
      rule.keywords.some((keyword) => text.includes(keyword)))
    .map((rule) => rule.server);
}

function yamlQuote(value) {
  return `"${String(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, '\\n')}"`;
}

// Riippuvuuskuvaus johdetaan plugarin mcp.json-palvelinmäärittelystä
// (ensimmäinen virke), jotta kuvauksella on yksi lähde eikä generaattoriin
// kerry palvelinkohtaisia vakiotekstejä.
function firstSentence(text) {
  const match = text.match(/^.*?[.!?](?=\s|$)/);
  return match ? match[0] : text;
}

function dependencyDescription(name, server) {
  const source = oneLine(server.description || server.title || name);
  return truncate(firstSentence(source), 160);
}

// stdio ja http ovat toisensa poissulkevat: palvelin, jolla ei ole
// kumpaakaan, on virhe lähteessä eikä saa tuottaa viallista openai.yamlia.
function serverTransport(pluginRoot, name, server) {
  if (server.url) return 'http';
  if (server.command) return 'stdio';
  return fail(
    `${pluginRoot}/mcp.json`,
    `palvelimella '${name}' ei ole url- eikä command-kenttää`,
  );
}

function renderOpenAIYaml(pluginRoot, dependencies, serverMap, skillMetadata) {
  const lines = [
    `${GENERATED_HEADER} Do not edit by hand.`,
    'interface:',
    `  display_name: ${yamlQuote(skillMetadata.name)}`,
    `  short_description: ${yamlQuote(truncate(skillMetadata.description, 160))}`,
    '',
    'dependencies:',
    '  tools:',
  ];

  for (const name of dependencies) {
    const server = serverMap[name];
    lines.push('    - type: "mcp"');
    lines.push(`      value: ${yamlQuote(name)}`);
    lines.push(`      description: ${yamlQuote(dependencyDescription(name, server))}`);

    if (serverTransport(pluginRoot, name, server) === 'http') {
      lines.push('      transport: "streamable_http"');
      lines.push(`      url: ${yamlQuote(server.url)}`);
    } else {
      lines.push('      transport: "stdio"');
      lines.push(`      command: ${yamlQuote(server.command)}`);
      if (Array.isArray(server.args) && server.args.length > 0) {
        lines.push('      args:');
        for (const arg of server.args) {
          lines.push(`        - ${yamlQuote(arg)}`);
        }
      }
    }
  }

  return `${lines.join('\n')}\n`;
}

function removeGeneratedText(path) {
  const fullPath = join(ROOT, path);
  if (!existsSync(fullPath)) return;
  const text = readFileSync(fullPath, 'utf8');
  if (!text.startsWith(GENERATED_HEADER)) return;
  unlinkSync(fullPath);
}

function writeSkillDependencyMetadata(pluginRoot, serverMap) {
  const serverNames = Object.keys(serverMap);
  const skillsDir = join(ROOT, pluginRoot, 'skills');

  for (const skillDir of listDirs(skillsDir)) {
    const skillName = basename(skillDir);
    const openAIYaml = `${pluginRoot}/skills/${skillName}/agents/openai.yaml`;
    const skillMd = join(skillDir, 'SKILL.md');
    if (!existsSync(skillMd)) {
      removeGeneratedText(openAIYaml);
      continue;
    }

    const skillText = readFileSync(skillMd, 'utf8');
    const skillPath = `${pluginRoot}/skills/${skillName}`;
    const dependencies = detectSkillDependencies(skillText, serverNames, skillPath);

    if (dependencies.length === 0) {
      removeGeneratedText(openAIYaml);
      continue;
    }

    const skillMetadata = readSkillMetadata(skillText, skillName);
    writeText(
      openAIYaml,
      renderOpenAIYaml(pluginRoot, dependencies, serverMap, skillMetadata),
    );
  }
}

function removeGeneratedSkillDependencyMetadata(pluginRoot) {
  const skillsDir = join(ROOT, pluginRoot, 'skills');

  for (const skillDir of listDirs(skillsDir)) {
    const skillName = basename(skillDir);
    removeGeneratedText(`${pluginRoot}/skills/${skillName}/agents/openai.yaml`);
  }
}

const marketplace = readJSON('marketplace.json');

// Claude-markkinapaikka: sama sisältö, mutta Anthropicin $schema takaisin.
// Neutraali lähde ei kanna harnessikohtaista skeemaviittausta.
const claudeMarketplace = {
  $schema: 'https://anthropic.com/claude-code/marketplace.schema.json',
  name: marketplace.name,
  description: marketplace.description,
  owner: marketplace.owner,
  plugins: marketplace.plugins.map((p) => ({
    name: p.name,
    displayName: p.displayName,
    source: p.source,
    description: p.description,
    author: p.author,
  })),
};

const codexMarketplace = {
  name: MARKETPLACE_NAME,
  interface: {
    displayName: MARKETPLACE_DISPLAY_NAME,
  },
  plugins: [],
};

for (const entry of marketplace.plugins) {
  const pluginRoot = entry.source.replace(/^\.\//, '');
  const manifest = readJSON(`${pluginRoot}/plugin.json`);

  if (manifest.name !== entry.name) {
    fail(
      `${pluginRoot}/plugin.json`,
      `name (${manifest.name}) != markkinapaikan name (${entry.name})`,
    );
  }

  // MCP: neutraali mcp.json -> .mcp.json-kuori Claudelle.
  const neutralMcp = join(ROOT, pluginRoot, 'mcp.json');
  const hasMcp = existsSync(neutralMcp);
  const mcpConfig = hasMcp ? readJSON(`${pluginRoot}/mcp.json`) : null;
  const serverMap = mcpConfig ? mcpConfig.mcpServers : null;

  if (hasMcp) {
    writeJSON(`${pluginRoot}/.mcp.json`, mcpConfig);
  } else {
    const staleShim = join(ROOT, pluginRoot, '.mcp.json');
    if (existsSync(staleShim)) unlinkSync(staleShim);
  }

  writeJSON(`${pluginRoot}/.claude-plugin/plugin.json`, {
    name: manifest.name,
    version: manifest.version,
    description: manifest.description,
    author: manifest.author,
  });

  const codexManifest = {
    name: manifest.name,
    version: manifest.version,
    description: manifest.description,
    author: manifest.author,
    homepage: `${REPOSITORY}/tree/main/${pluginRoot}`,
    repository: REPOSITORY,
    license: 'MIT',
    keywords: ['legal', 'finland', 'finnish-law', entry.name],
    skills: './skills/',
    interface: {
      displayName: entry.displayName || entry.name,
      shortDescription: truncate(manifest.description, 160),
      longDescription: entry.description || manifest.description,
      developerName: entry.author?.name || manifest.author?.name || marketplace.owner?.name,
      category: CATEGORY,
      capabilities: hasMcp ? ['Skills', 'MCP'] : ['Skills'],
      defaultPrompt: [
        truncate(`Käytä ${entry.displayName || entry.name} -plugaria Suomen oikeuden tehtävään.`, 120),
      ],
    },
  };

  if (hasMcp) {
    codexManifest.mcpServers = './.mcp.json';
    const staleCodexMcpPath = join(ROOT, pluginRoot, '.codex-plugin/mcp.json');
    if (existsSync(staleCodexMcpPath)) {
      unlinkSync(staleCodexMcpPath);
    }
    writeSkillDependencyMetadata(pluginRoot, serverMap);
  } else {
    removeGeneratedSkillDependencyMetadata(pluginRoot);
  }

  writeJSON(`${pluginRoot}/.codex-plugin/plugin.json`, codexManifest);

  codexMarketplace.plugins.push({
    name: entry.name,
    source: {
      source: 'local',
      path: entry.source,
    },
    policy: {
      installation: 'AVAILABLE',
      authentication: 'ON_INSTALL',
    },
    category: CATEGORY,
  });
}

writeJSON('.claude-plugin/marketplace.json', claudeMarketplace);
writeJSON('.agents/plugins/marketplace.json', codexMarketplace);
console.log(`Adapterit generoitu: ${codexMarketplace.plugins.length} plugaria.`);
